/* ============================================================
   UTILS — formatting, toasts, exports (Excel / PDF / Print)
   ============================================================ */
window.U = (function () {

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  function num(v) { var n = Number(v); return isNaN(n) ? 0 : n; }

  function fmtQty(v) {
    var n = num(v);
    return (n % 1 === 0) ? n.toLocaleString('en-IN') : n.toLocaleString('en-IN', { maximumFractionDigits: 2 });
  }

  function fmtDate(v) {
    if (!v) return '';
    var d = new Date(v);
    if (isNaN(d.getTime())) return String(v);
    return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  }

  function todayISO() {
    var d = new Date();
    return d.getFullYear() + '-' + ('0' + (d.getMonth() + 1)).slice(-2) + '-' + ('0' + d.getDate()).slice(-2);
  }

  function debounce(fn, ms) {
    var t;
    return function () {
      var args = arguments, ctx = this;
      clearTimeout(t);
      t = setTimeout(function () { fn.apply(ctx, args); }, ms);
    };
  }

  /* ---------- toasts ---------- */
  function toast(msg, type) {
    var el = document.createElement('div');
    el.className = 'toast toast-' + (type || 'info');
    el.textContent = msg;
    document.getElementById('toasts').appendChild(el);
    setTimeout(function () { el.classList.add('show'); }, 10);
    setTimeout(function () {
      el.classList.remove('show');
      setTimeout(function () { el.remove(); }, 300);
    }, 3500);
  }

  /* ---------- status pills ---------- */
  function pill(text, kind) {
    return '<span class="pill pill-' + kind + '">' + esc(text) + '</span>';
  }

  function orderStatusPill(status) {
    var map = { 'Open': 'info', 'In Production': 'warn', 'Ready': 'good', 'Dispatched': 'info', 'Delivered': 'good', 'Cancelled': 'bad' };
    return pill(status, map[status] || 'muted');
  }

  function prStatusPill(status) {
    var map = { 'Pending': 'warn', 'Approved': 'info', 'Ordered': 'info', 'Received': 'good', 'Cancelled': 'bad' };
    return pill(status, map[status] || 'muted');
  }

  /* ---------- Excel export (SheetJS) ---------- */
  function exportExcel(filename, sheetsSpec) {
    // sheetsSpec: [{name, headers:[], rows:[[..],..]}]
    var wb = XLSX.utils.book_new();
    sheetsSpec.forEach(function (s) {
      var aoa = [s.headers].concat(s.rows);
      var ws = XLSX.utils.aoa_to_sheet(aoa);
      ws['!cols'] = s.headers.map(function (h, i) {
        var w = String(h).length;
        s.rows.forEach(function (r) { w = Math.max(w, String(r[i] == null ? '' : r[i]).length); });
        return { wch: Math.min(w + 2, 40) };
      });
      XLSX.utils.book_append_sheet(wb, ws, s.name.substring(0, 31));
    });
    XLSX.writeFile(wb, filename);
  }

  /* ---------- PDF export (jsPDF + autotable) ---------- */
  function pdfDoc(title, subtitleLines) {
    var jsPDFCtor = window.jspdf.jsPDF;
    var doc = new jsPDFCtor({ unit: 'pt', format: 'a4' });
    var cfg = window.KMS_CONFIG;
    var W = doc.internal.pageSize.getWidth();

    // header band
    doc.setFillColor(16, 66, 129); // deep blue
    doc.rect(0, 0, W, 64, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(cfg.COMPANY_NAME, 40, 28);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(cfg.COMPANY_TAGLINE, 40, 44);

    doc.setTextColor(11, 11, 11);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(title, 40, 92);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(82, 81, 78);
    var y = 108;
    (subtitleLines || []).forEach(function (line) {
      doc.text(line, 40, y);
      y += 13;
    });
    return { doc: doc, startY: y + 8 };
  }

  function pdfTable(doc, startY, headers, rows) {
    doc.autoTable({
      startY: startY,
      head: [headers],
      body: rows,
      styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 5, textColor: [11, 11, 11] },
      headStyles: { fillColor: [16, 66, 129], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [246, 248, 251] },
      margin: { left: 40, right: 40 }
    });
    return doc.lastAutoTable.finalY;
  }

  function pdfFooter(doc) {
    var pages = doc.internal.getNumberOfPages();
    var W = doc.internal.pageSize.getWidth();
    var H = doc.internal.pageSize.getHeight();
    for (var i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(137, 135, 129);
      doc.text('Generated by ' + window.KMS_CONFIG.COMPANY_NAME + ' Kitting Management System — ' + new Date().toLocaleString('en-IN'), 40, H - 24);
      doc.text('Page ' + i + ' of ' + pages, W - 80, H - 24);
    }
  }

  /* ---------- Print (opens a clean print window) ---------- */
  function printHTML(title, bodyHTML) {
    var w = window.open('', '_blank');
    w.document.write(
      '<html><head><title>' + esc(title) + '</title><style>' +
      'body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#0b0b0b;margin:32px;}' +
      'h1{font-size:20px;margin:0 0 4px;} .sub{color:#52514e;font-size:12px;margin-bottom:16px;}' +
      'table{border-collapse:collapse;width:100%;font-size:12px;}' +
      'th{background:#104281;color:#fff;text-align:left;padding:6px 8px;}' +
      'td{border-bottom:1px solid #e1e0d9;padding:6px 8px;}' +
      '@media print{button{display:none}}' +
      '</style></head><body>' + bodyHTML +
      '<script>window.onload=function(){window.print();}<\/script></body></html>'
    );
    w.document.close();
  }

  return {
    esc: esc, num: num, fmtQty: fmtQty, fmtDate: fmtDate, todayISO: todayISO,
    debounce: debounce, toast: toast, pill: pill,
    orderStatusPill: orderStatusPill, prStatusPill: prStatusPill,
    exportExcel: exportExcel, pdfDoc: pdfDoc, pdfTable: pdfTable, pdfFooter: pdfFooter,
    printHTML: printHTML
  };
})();
